name: Git Pages

on:
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl --fail https://morgancreekmore.me/ -X PUT --data "https://github.com/gamingrobot/morgancreekmore.me.git"
          curl --fail https://www.morgancreekmore.me/ -X PUT --data "https://github.com/gamingrobot/morgancreekmore.me.git"
